#ifndef MICROBYTE_RTOS_CONFIG_H
#define MICROBYTE_RTOS_CONFIG_H

#define MICROBYTE_RTOS_CONFIG_H_IN

#ifdef MICROBYTE_RTOS_PROJECT_CONFIG_FILE
#include MICROBYTE_RTOS_PROJECT_CONFIG_FILE
#endif

// MicroByte RTOS default config

#ifndef MICROBYTE_CONFIG_THREAD_PRIO_LEVELS
#define MICROBYTE_CONFIG_THREAD_PRIO_LEVELS (16)
#endif

#ifndef MICROBYTE_CONFIG_THREAD_MAX
#define MICROBYTE_CONFIG_THREAD_MAX (32)
#endif

#ifndef MICROBYTE_CONFIG_MSG_QUEUE_SIZE
#define MICROBYTE_CONFIG_MSG_QUEUE_SIZE (4)
#endif

#ifndef MICROBYTE_CONFIG_HEAP_SIZE
#define MICROBYTE_CONFIG_HEAP_SIZE (1568 * sizeof(void *))
#endif

#ifndef MICROBYTE_CONFIG_TIMER_USEC_BASE_FREQ
#define MICROBYTE_CONFIG_TIMER_USEC_BASE_FREQ (1000000LU)
#endif

#ifndef MICROBYTE_CONFIG_TIMER_USEC_DEV
#define MICROBYTE_CONFIG_TIMER_USEC_DEV (0)
#endif

#ifndef MICROBYTE_CONFIG_TIMER_USEC_MIN
#define MICROBYTE_CONFIG_TIMER_USEC_MIN (10)
#endif

#undef MICROBYTE_RTOS_CONFIG_H_IN

#endif /* MICROBYTE_RTOS_CONFIG_H */
